import sys
import os
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings