# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec file for Taurus Executor
Packages executor_core into a standalone binary executable.

Usage:
    pyinstaller scripts/taurus-executor.spec
"""

import sys
import os
from pathlib import Path

# Project root directory (parent of scripts/)
project_root = Path(SPECPATH).parent
src_dir = str(project_root / 'src')

# Ensure src directory is in path for imports
sys.path.insert(0, src_dir)

block_cipher = None

# Collect all hidden imports
hidden_imports = [
    # gRPC and protobuf
    'grpc',
    'grpc._cython',
    'grpc._cython.cygrpc',
    'grpc.framework',
    'grpc.framework.foundation',
    'google.protobuf',
    'google.protobuf.descriptor',
    'google.protobuf.descriptor_pool',
    'google.protobuf.internal',
    'google.protobuf.pyext',
    'google.rpc',
    'google.rpc.status_pb2',
    
    # Async support
    'asyncio',
    'asyncio.events',
    'asyncio.base_events',
    'asyncio.unix_events',
    'asyncio.windows_events',
    'concurrent.futures',
    'concurrent.futures.thread',
    'concurrent.futures.process',
    
    # Network and HTTP
    'aiohttp',
    'aiohttp.web',
    'aiohttp.client',
    'aiohttp.web_app',
    'aiohttp.web_runner',
    'aiohttp.web_protocol',
    'aiohttp.http',
    'aiohttp.http_parser',
    'aiohttp.http_writer',
    'aiohttp.http_reader',
    'aiohttp.multipart',
    'aiohttp.streams',
    'aiohttp.resolver',
    'aiohttp.connector',
    'aiohttp.client_reqrep',
    'aiohttp.client_exceptions',
    'aiohttp.helpers',
    'aiohttp.log',
    'aiohttp.abc',
    'aiohttp.typedefs',
    'aiohttp.payload',
    'aiohttp.formdata',
    'aiohttp.cookiejar',
    'aiohttp.proxy',
    'aiohttp.web_exceptions',
    'aiohttp.web_request',
    'aiohttp.web_response',
    'aiohttp.web_urldispatcher',
    'aiohttp.web_fileresponse',
    'aiohttp.web_ws',
    'aiohttp._websocket',
    'aiohttp_cors',
    'httpx',
    'httpx._client',
    'httpx._transports',
    'httpx._transports.default',
    'httpcore',
    'httpcore._async',
    'httpcore._async.http11',
    'httpcore._async.http2',
    'httpcore._async.connection',
    'httpcore._async.connection_pool',
    'h11',
    'h2',
    'h2.connection',
    'h2.events',
    'h2.settings',
    'h2.stream',
    'hpack',
    'hyperframe',
    
    # SSH and crypto (paramiko)
    'paramiko',
    'paramiko.transport',
    'paramiko.client',
    'paramiko.ssh_exception',
    'paramiko.auth_handler',
    'paramiko.channel',
    'paramiko.message',
    'paramiko.packet',
    'paramiko.kex_ecdh_nist',
    'paramiko.ecdsakey',
    'paramiko.ed25519key',
    'paramiko.rsakey',
    'paramiko.dsskey',
    'cryptography',
    'cryptography.hazmat',
    'cryptography.hazmat.backends',
    'cryptography.hazmat.backends.openssl',
    'cryptography.hazmat.primitives',
    'cryptography.hazmat.primitives.asymmetric',
    'cryptography.hazmat.primitives.asymmetric.rsa',
    'cryptography.hazmat.primitives.asymmetric.ec',
    'cryptography.hazmat.primitives.asymmetric.ed25519',
    'cryptography.hazmat.primitives.serialization',
    'cryptography.hazmat.primitives.ciphers',
    'cryptography.hazmat.primitives.ciphers.algorithms',
    'cryptography.hazmat.primitives.ciphers.modes',
    'cryptography.hazmat.primitives.hashes',
    'cryptography.hazmat.primitives.hmac',
    'cryptography.x509',
    'cryptography.x509.oid',
    'bcrypt',
    'nacl',
    'nacl.signing',
    'nacl.exceptions',
    'pynacl',
    
    # System monitoring (psutil)
    'psutil',
    'psutil._pslinux',
    'psutil._psposix',
    'psutil._psutil_linux',
    'psutil._psutil_posix',
    
    # Interactive process control
    'pexpect',
    'pexpect.pty_spawn',
    'pexpect.utils',
    'pexpect.exceptions',
    'ptyprocess',
    'ptyprocess.ptyprocess',
    
    # File operations
    'aiofiles',
    'aiofiles.os',
    'aiofiles.threadpool',
    
    # UI and formatting
    'rich',
    'rich.console',
    'rich.logging',
    'rich.traceback',
    'rich.text',
    'rich.panel',
    'rich.table',
    'markdown',
    'markdown.extensions',
    'markdown.inlinepatterns',
    'markdown.blockprocessors',
    'markdown.treeprocessors',
    'markdown.preprocessors',
    'markdown.postprocessors',
    'pygments',
    'pygments.lexers',
    'pygments.formatters',
    'pygments.styles',
    
    # Configuration
    'pydantic',
    'pydantic.fields',
    'pydantic.env_settings',
    'dotenv',
    'dotenv.main',
    
    # Metrics
    'prometheus_client',
    'prometheus_client.core',
    'prometheus_client.metrics',
    'prometheus_client.registry',
    'prometheus_client.values',
    'prometheus_client.decorator',
    
    # Standard library modules that might be missed
    'socketserver',
    'multiprocessing',
    'multiprocessing.connection',
    'multiprocessing.reduction',
    'ssl',
    'hashlib',
    'hmac',
    'secrets',
    'tempfile',
    'subprocess',
    'shutil',
    'pathlib',
    'json',
    'csv',
    'xml',
    'xml.etree',
    'xml.etree.ElementTree',
    'logging',
    'logging.handlers',
    'email',
    'email.mime',
    'email.mime.text',
    'email.mime.multipart',
    'email.mime.base',
    'email.mime.nonmultipart',
    'email.mime.application',
    'email.charset',
    'email.encoders',
    'email.errors',
    'email.feedparser',
    'email.generator',
    'email.header',
    'email.iterators',
    'email.message',
    'email.parser',
    'email.policy',
    'email.quoprimime',
    'email.base64mime',
    'email.utils',
    'urllib',
    'urllib.parse',
    'urllib.request',
    'urllib.response',
    'urllib.error',
    'http',
    'http.client',
    'http.server',
    'http.cookies',
    'http.cookiejar',
    'mimetypes',
    'base64',
    'binascii',
    'quopri',
    'uu',
    'cgi',
    'cgitb',
    'webbrowser',
    'getpass',
    'locale',
    'gettext',
    'calendar',
    'collections',
    'collections.abc',
    'itertools',
    'operator',
    'functools',
    'contextlib',
    'abc',
    'io',
    'codecs',
    'struct',
    'array',
    'enum',
    'types',
    'weakref',
    'copy',
    'pprint',
    'reprlib',
    'textwrap',
    'string',
    'stringprep',
    're',
    'sre_compile',
    'sre_constants',
    'sre_parse',
    'fnmatch',
    'glob',
    'stat',
    'posixpath',
    'ntpath',
    'genericpath',
    'os',
    'posix',
    'pwd',
    'grp',
    'resource',
    'select',
    'selectors',
    'signal',
    'mmap',
    'errno',
    'ctypes',
    'ctypes.util',
    'threading',
    'queue',
    '_thread',
    'dummy_threading',
    'sched',
    'time',
    'datetime',
    'zoneinfo',
    'math',
    'cmath',
    'decimal',
    'fractions',
    'random',
    'statistics',
    'dataclasses',
    'typing',
    'typing_extensions',
    'inspect',
    'dis',
    'pickle',
    'pickletools',
    'shelve',
    'dbm',
    'gzip',
    'bz2',
    'lzma',
    'zipfile',
    'tarfile',
    'zlib',
    'zipimport',
    'pkgutil',
    'importlib',
    'importlib.abc',
    'importlib.machinery',
    'importlib.metadata',
    'importlib.resources',
    'importlib.util',
    'site',
    'sysconfig',
    'platform',
    'atexit',
    'faulthandler',
    'gc',
    'traceback',
    'linecache',
    'token',
    'tokenize',
    'keyword',
    'ast',
    'symtable',
    'compileall',
    'py_compile',
    'warnings',
    'contextvars',
    'graphlib',
    'colorsys',
    'imghdr',
    'sndhdr',
    'ossaudiodev',
    'aifc',
    'sunau',
    'wave',
    'chunk',
    'colorsys',
    'argparse',
    'getopt',
    'optparse',
]

# Collect data files
datas = [
    # Include generated gRPC code
    (str(project_root / 'src/executor_core/services/generated'), 'executor_core/services/generated'),
    # Include proto files (may be needed for reference)
    (str(project_root / 'proto'), 'proto'),
]

# Collect binaries
binaries = []

# Analysis
a = Analysis(
    [str(project_root / 'src/executor_core/main.py')],
    pathex=[src_dir],
    binaries=binaries,
    datas=datas,
    hiddenimports=hidden_imports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'scipy',
        'pandas',
        'IPython',
        'jupyter',
        'notebook',
        'test',
        'tests',
        'pytest',
        'unittest',
        'mock',
        'sphinx',
        'docutils',
        'pydoc',
        'idlelib',
        'lib2to3',
        'ensurepip',
        'venv',
        'pip',
        'wheel',
        '_tkinter',
        'Tkinter',
        'PyQt5',
        'PyQt4',
        'PySide',
        'PySide2',
        'wx',
        'gi',
        'gtk',
        'glib',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

# PyInstaller optimization
pyz = PYZ(
    a.pure,
    a.zipped_data,
    cipher=block_cipher,
)

# Build executable
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='taurus-executor',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)